### ISSUE TITLE
t/codecov/001_lint.t test fails

### ISSUE THREAD

**Issue by eserte** [pine613/p5-Devel-Cover-Report-Codecov#3]
See http://matrix.cpantesters.org/?dist=Devel-Cover-Report-Codecov%200.02 for a pass/fail overview and http://www.cpantesters.org/cpan/report/9e839130-3884-11e5-a271-6086e0bfc7aa for a sample fail report.

**Comment by pine613** [comment]
Thanks! I'll check it later.

**Comment by pine613** [comment]
I think you environment had installed Perl::Critic::OTRS.
This module is **not** required Perl::Critic::OTRS.

http://search.cpan.org/~reneeb/Perl-Critic-OTRS-0.05/lib/Perl/Critic/OTRS.pm

**Comment by pine613** [comment]
f690e05d556f08f5a910249df21b88ea81360166 I've changed perlcriticrc to limit without standard policies.
Thank you.
